name: Config Generator
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Docs Branch'
        required: true
        default: 'master'
      repoBranch:
        description: 'Project Branch'
        required: true
        default: 'master'
      repo:
        description: 'Project ID. Allowed values: gateway, dashboard, pump, mdcb'
        required: true
        default: ''

jobs:
  config-gen:
    env:
      REPO: ${{ github.event.inputs.repo }}
      BRANCH: ${{ github.event.inputs.repoBranch }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        path: ./tyk-docs
        token: ${{ secrets.ORG_GH_TOKEN }}
        ref: ${{ github.event.inputs.branch }}

    - name: Checkout Config Generator Repo
      uses: actions/checkout@master
      with:
        repository: TykTechnologies/tyk-config-info-generator
        path: ./tyk-config-info-generator
        token: ${{ secrets.ORG_GH_TOKEN }}

    - name: Generate markdown
      run: |
        cd ./tyk-config-info-generator/src
        sudo TOKEN=${{ secrets.ORG_GH_TOKEN }} node app.js ${{ github.event.inputs.repo }}:${{ github.event.inputs.repoBranch }}
        cp /node/home/tyk-config-info-generator/info/${{ github.event.inputs.repoBranch }}/${{ github.event.inputs.repo }}.md ../../tyk-docs/tyk-docs/content/shared/${{ github.event.inputs.repo }}-config.md

    - name: Raise configuration changes Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        commit-message: update config
        title: Updated configuration documentation $REPO:$BRANCH
        body: Updated config field doc for Tyk $REPO $BRANCH
        branch: update-config-$REPO:$BRANCH
        branch-suffix: random
        delete-branch: true
