# This workflow will update the OAS docs on tyk-docs

name: Update OAS docs

on:
  workflow_dispatch:
  repository_dispatch:
    types: [tyk-oas-docs]

env:
  TYK_SHA: ${{ github.event.client_payload.sha }}
  TYK_REF: ${{ github.event.client_payload.ref }}
  GOPRIVATE: github.com/TykTechnologies

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: checkout tyk-docs/${{ env.TYK_REF }}
        uses: actions/checkout@master
        with:
          token: ${{ secrets.ORG_GH_TOKEN }}
          ref: ${{ env.TYK_REF }}
          path: ./tyk-docs

      - name: checkout tyk/${{ env.TYK_SHA }}
        uses: actions/checkout@master
        with:
          repository: TykTechnologies/tyk
          token: ${{ secrets.ORG_GH_TOKEN }}
          ref: ${{ env.TYK_SHA }}
          path: ./tyk

      - name: Copy OAS Docs
        run: |
          cat ./tyk/apidef/oas/schema/x-tyk-gateway.md > ./tyk-docs/tyk-docs/content/shared/x-tyk-gateway.md

      - name: Raise pull request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: import OAS API Object from ${{ env.TYK_REF }}
          title: import OAS API Object from ${{ env.TYK_REF }}
          branch: ${{ env.TYK_REF }}/update-oas-docs
          path: ./tyk-docs
          branch-suffix: random
          delete-branch: true
          reviewers: letzya, Keithwachira
